#!/usr/bin/env python3
"""Generate an index.md listing a directory's own contents (like `ls`, MkDocs has no such built-in).

Subfolders and files are listed as two separate, alphabetically sorted
groups. Regenerates one index.md per directory; by default walks the
whole tree so every subfolder link resolves to a real page.

Usage:
    python py/mkdocs_index.py docs/my-md
    python py/mkdocs_index.py docs/my-md --no-recursive
"""

from __future__ import annotations

import argparse
from pathlib import Path

GENERATED_MARK = "<!-- generated by py/mkdocs_index.py — do not hand-edit, it will be overwritten -->"

SKIP_NAMES = {"index.md", ".git", "__pycache__"}
SKIP_SUFFIXES = {".swp", ".swo"}
# Directories that hold referenced static resources (JS/CSS/models), not
# browsable content — never listed, never recursed into.
DEFAULT_EXCLUDE_DIRS = {"assets"}


def _visible(path: Path, exclude_dirs: set[str]) -> bool:
    if path.name.startswith("."):
        return False
    if path.name in SKIP_NAMES:
        return False
    if path.suffix in SKIP_SUFFIXES:
        return False
    if path.is_dir() and path.name in exclude_dirs:
        return False
    return True


def render_index(dir_path: Path, title: str | None = None, exclude_dirs: set[str] | None = None) -> str:
    exclude_dirs = exclude_dirs if exclude_dirs is not None else DEFAULT_EXCLUDE_DIRS
    entries = [p for p in dir_path.iterdir() if _visible(p, exclude_dirs)]
    subdirs = sorted((p for p in entries if p.is_dir()), key=lambda p: p.name)
    files = sorted((p for p in entries if p.is_file()), key=lambda p: p.name)

    lines = [GENERATED_MARK, "", f"# {title or dir_path.name}", ""]

    if subdirs:
        lines.append("## Folders")
        lines.append("")
        for d in subdirs:
            lines.append(f"- [{d.name}/]({d.name}/)")
        lines.append("")

    if files:
        lines.append("## Files")
        lines.append("")
        for f in files:
            lines.append(f"- [{f.stem}]({f.name})")
        lines.append("")

    if not subdirs and not files:
        lines.append("*(empty)*")
        lines.append("")

    return "\n".join(lines)


def build(dir_path: Path, recursive: bool = True, exclude_dirs: set[str] | None = None) -> None:
    exclude_dirs = exclude_dirs if exclude_dirs is not None else DEFAULT_EXCLUDE_DIRS
    (dir_path / "index.md").write_text(render_index(dir_path, exclude_dirs=exclude_dirs), encoding="utf-8")
    print(f"wrote {dir_path / 'index.md'}")
    if not recursive:
        return
    for child in sorted(p for p in dir_path.iterdir() if p.is_dir() and _visible(p, exclude_dirs)):
        build(child, recursive=True, exclude_dirs=exclude_dirs)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("dir", type=Path, help="Directory to index (index.md is written here)")
    p.add_argument(
        "--no-recursive",
        dest="recursive",
        action="store_false",
        help="Only index this one directory, not its subfolders",
    )
    p.add_argument(
        "--exclude",
        action="append",
        default=None,
        help=f"Directory name to skip entirely (repeatable). Default: {sorted(DEFAULT_EXCLUDE_DIRS)}",
    )
    args = p.parse_args()

    if not args.dir.is_dir():
        raise SystemExit(f"not a directory: {args.dir}")

    exclude_dirs = set(args.exclude) if args.exclude else DEFAULT_EXCLUDE_DIRS
    build(args.dir, recursive=args.recursive, exclude_dirs=exclude_dirs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
