#!/usr/bin/env python3
"""Split a large Chinese-language markdown notebook into a manifest-driven set of files.

Three-step workflow:
    1. scan  — parse the source file, compute split boundaries, write an
               editable YAML manifest (no .md files written yet).
    2. (you edit the manifest by hand if any filename looks wrong)
    3. split — read the manifest and actually write the split files.
    merge    — reverse the split: reassemble one file from the manifest
               (or from each piece's translated counterpart with --en).
    index    — write an index.md grouping pieces by level-1 section.

The manifest (with its absolute source path) always stays under tmp/history_notes/
— never point --outdir for split/merge/index at the manifest's own directory if
that directory is inside docs/, since MkDocs publishes everything under docs_dir
as static files and the manifest's `source:` field would leak a local filesystem
path onto the public site.

Usage:
    python py/split.py scan --source /home/za/my/history/2021/notebook.history.md --outdir tmp/history_notes
    python py/split.py split --manifest tmp/history_notes/manifest.yaml --outdir docs/history_notes
    python py/split.py index --manifest tmp/history_notes/manifest.yaml --outdir docs/history_notes
    python py/split.py merge /tmp/test.merge.md --manifest tmp/history_notes/manifest.yaml --outdir docs/history_notes
    python py/split.py merge /tmp/test.merge.en.md --manifest tmp/history_notes/manifest.yaml --outdir docs/history_notes --en
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import yaml
from pypinyin import Style, lazy_pinyin

MAX_LINES = 999
LEVEL1_RE = re.compile(r"^#(?!#)")
DATE_RE = re.compile(r"^\d{4}")
MANIFEST_HEADER = (
    "# Generated by py/split.py scan — edit filenames/titles below if needed,\n"
    "# then run: python py/split.py split --manifest <this file>\n"
)


def extract_phrase(title: str) -> str:
    candidates = [i for i in (title.find("，"), title.find(",")) if i != -1]
    if candidates:
        return title[: min(candidates)].strip()
    dash = title.find(" - ")
    if dash != -1:
        return title[:dash].strip()
    return title.strip()


def slugify(phrase: str) -> str:
    tokens = lazy_pinyin(phrase, style=Style.NORMAL)
    raw = "-".join(tokens).lower()
    raw = re.sub(r"[^a-z0-9]+", "-", raw)
    raw = re.sub(r"-+", "-", raw).strip("-")
    return raw or "section"


def suffix_codes(n: int) -> list[str]:
    """n fixed-width lowercase-letter codes (a, b, ... or aa, ab, ... if n > 26),
    never mixing widths within one call — so plain string sort matches order."""
    width = 1
    while 26**width < n:
        width += 1
    codes = []
    for i in range(n):
        x, code = i, ""
        for _ in range(width):
            code = chr(ord("a") + x % 26) + code
            x //= 26
        codes.append(code)
    return codes


def paragraph_cut(lines: list[str], start: int, limit: int) -> int:
    for i in range(min(limit, len(lines) - 1), start, -1):
        if lines[i].strip() == "":
            return i + 1
    return limit


def split_section(lines: list[str]) -> list[tuple[int, int]]:
    """Return [(start, end)) pieces, 0-based local to the section, end-exclusive."""
    n = len(lines)
    if n <= MAX_LINES:
        return [(0, n)]
    boundaries = [i for i, l in enumerate(lines) if i > 0 and DATE_RE.match(l)]
    pieces: list[tuple[int, int]] = []
    start = 0
    while start < n:
        limit = start + MAX_LINES
        reachable = [b for b in boundaries if start < b <= limit]
        if reachable:
            end = reachable[-1]
        elif n - start <= MAX_LINES:
            end = n
        else:
            end = paragraph_cut(lines, start, limit)
        pieces.append((start, end))
        start = end
    return pieces


def find_level1_bounds(all_lines: list[str]) -> list[tuple[int, int]]:
    """Return [(start, end)) sections, 0-based global, end-exclusive."""
    heads = [i for i, l in enumerate(all_lines) if LEVEL1_RE.match(l)]
    if not heads:
        raise SystemExit("no level-1 '# ' headings found in source")
    bounds = []
    for i, h in enumerate(heads):
        end = heads[i + 1] if i + 1 < len(heads) else len(all_lines)
        bounds.append((h, end))
    return bounds


def build_manifest(source: Path) -> dict:
    all_lines = source.read_text(encoding="utf-8").splitlines(keepends=True)
    entries = []
    for idx, (sec_start, sec_end) in enumerate(find_level1_bounds(all_lines), start=1):
        sec_lines = all_lines[sec_start:sec_end]
        title = sec_lines[0].lstrip("#").strip()
        phrase = extract_phrase(title)
        slug = slugify(phrase)
        base = f"{idx:02d}_{slug}"
        pieces = split_section(sec_lines)
        codes = suffix_codes(len(pieces))
        for p_i, (local_start, local_end) in enumerate(pieces):
            stem = base if len(pieces) == 1 else f"{base}_{codes[p_i]}"
            g_start = sec_start + local_start
            g_end = sec_start + local_end  # 0-based exclusive == 1-based inclusive last line
            entries.append(
                {
                    "filename": f"{stem}.md",
                    "title": title,
                    "start_line": g_start + 1,
                    "end_line": g_end,
                    "line_count": g_end - g_start,
                    "translate_filename": f"{stem}-en.md",
                }
            )
    return {"source": str(source.resolve()), "entries": entries}


def cmd_scan(args: argparse.Namespace) -> int:
    source = Path(args.source)
    if not source.is_file():
        raise SystemExit(f"not a file: {source}")
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    manifest = build_manifest(source)
    manifest_path = outdir / "manifest.yaml"
    text = MANIFEST_HEADER + yaml.safe_dump(manifest, allow_unicode=True, sort_keys=False, default_flow_style=False)
    manifest_path.write_text(text, encoding="utf-8")
    print(f"wrote {manifest_path} ({len(manifest['entries'])} entries)")
    return 0


def load_manifest(manifest_path: Path) -> dict:
    with manifest_path.open(encoding="utf-8") as f:
        manifest = yaml.safe_load(f)
    if not manifest or "entries" not in manifest or "source" not in manifest:
        raise SystemExit(f"malformed manifest: {manifest_path}")
    return manifest


def validate_entries(entries: list[dict], total_lines: int) -> None:
    ordered = sorted(entries, key=lambda e: e["start_line"])
    seen_names = set()
    for e in ordered:
        if e["filename"] in seen_names:
            raise SystemExit(f"duplicate filename in manifest: {e['filename']}")
        seen_names.add(e["filename"])
    if ordered[0]["start_line"] != 1:
        raise SystemExit(f"manifest does not start at line 1 (starts at {ordered[0]['start_line']})")
    for a, b in zip(ordered, ordered[1:]):
        if a["end_line"] + 1 != b["start_line"]:
            raise SystemExit(
                f"gap/overlap between {a['filename']} (ends {a['end_line']}) "
                f"and {b['filename']} (starts {b['start_line']})"
            )
    if ordered[-1]["end_line"] != total_lines:
        raise SystemExit(
            f"manifest does not cover the whole source "
            f"(ends at {ordered[-1]['end_line']}, source has {total_lines} lines)"
        )


def zatranslate_block(translate_filename: str) -> str:
    return (
        "\n<!-- zatranslate\n"
        f"target = {translate_filename}\n"
        "from = cn\n"
        "to = en\n"
        "translate_whole = true\n"
        "block_size = 300\n"
        "-->\n"
    )


def cmd_split(args: argparse.Namespace) -> int:
    manifest_path = Path(args.manifest)
    manifest = load_manifest(manifest_path)
    source = Path(args.source) if args.source else Path(manifest["source"])
    if not source.is_file():
        raise SystemExit(f"not a file: {source}")
    all_lines = source.read_text(encoding="utf-8").splitlines(keepends=True)
    validate_entries(manifest["entries"], len(all_lines))

    outdir = Path(args.outdir) if args.outdir else manifest_path.parent
    outdir.mkdir(parents=True, exist_ok=True)
    for e in manifest["entries"]:
        piece_lines = all_lines[e["start_line"] - 1 : e["end_line"]]
        content = "".join(piece_lines)
        if not content.endswith("\n"):
            content += "\n"
        content += zatranslate_block(e["translate_filename"])
        (outdir / e["filename"]).write_text(content, encoding="utf-8")
    print(f"wrote {len(manifest['entries'])} files to {outdir}")
    return 0


def cmd_merge(args: argparse.Namespace) -> int:
    manifest_path = Path(args.manifest)
    manifest = load_manifest(manifest_path)
    outdir = Path(args.outdir) if args.outdir else manifest_path.parent
    key = "translate_filename" if args.en else "filename"

    missing = [e[key] for e in manifest["entries"] if not (outdir / e[key]).is_file()]
    if missing:
        raise SystemExit("missing files, run split first (or translate) — not found:\n" + "\n".join(missing))

    parts = []
    for e in manifest["entries"]:
        content = (outdir / e[key]).read_text(encoding="utf-8")
        if not args.en:
            block = zatranslate_block(e["translate_filename"])
            if content.endswith(block):
                content = content[: -len(block)]
        parts.append(content)

    out_path = Path(args.output)
    out_path.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {out_path}")
    return 0


def cmd_index(args: argparse.Namespace) -> int:
    manifest_path = Path(args.manifest)
    manifest = load_manifest(manifest_path)

    groups: dict[str, list[dict]] = {}
    order: list[str] = []
    for e in manifest["entries"]:
        key = e["filename"].split("_", 1)[0]
        if key not in groups:
            groups[key] = []
            order.append(key)
        groups[key].append(e)

    lines = ["# History Notes", ""]
    for key in order:
        pieces = groups[key]
        title = pieces[0]["title"]
        lines.append(f"- [{title}]({pieces[0]['filename']})")
        if len(pieces) > 1:
            for i, piece in enumerate(pieces, start=1):
                lines.append(f"    - [Part {i}]({piece['filename']})")
    lines.append("")

    content_dir = Path(args.outdir) if args.outdir else manifest_path.parent
    out_path = content_dir / "index.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_path} ({len(order)} sections, {len(manifest['entries'])} pieces)")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="command", required=True)

    p_scan = sub.add_parser("scan", help="parse source, write an editable manifest.yaml")
    p_scan.add_argument("--source", required=True, help="path to the source markdown file")
    p_scan.add_argument("--outdir", default="tmp/history_notes", help="where manifest.yaml is written")
    p_scan.set_defaults(func=cmd_scan)

    p_split = sub.add_parser("split", help="write split files per the manifest")
    p_split.add_argument("--manifest", required=True, help="path to manifest.yaml")
    p_split.add_argument("--source", default=None, help="override source path stored in the manifest")
    p_split.add_argument(
        "--outdir", default=None, help="where content files are written (default: manifest's own directory)"
    )
    p_split.set_defaults(func=cmd_split)

    p_merge = sub.add_parser("merge", help="reassemble one file from the manifest's pieces")
    p_merge.add_argument("output", help="path to write the merged file")
    p_merge.add_argument("--manifest", required=True, help="path to manifest.yaml")
    p_merge.add_argument("--en", action="store_true", help="merge each piece's translate_filename instead")
    p_merge.add_argument(
        "--outdir", default=None, help="where content files are read from (default: manifest's own directory)"
    )
    p_merge.set_defaults(func=cmd_merge)

    p_index = sub.add_parser("index", help="write an index.md grouping pieces by level-1 section")
    p_index.add_argument("--manifest", required=True, help="path to manifest.yaml")
    p_index.add_argument(
        "--outdir", default=None, help="directory to write index.md into (default: manifest's own directory)"
    )
    p_index.set_defaults(func=cmd_index)

    args = p.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
